name: Create Empty Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          DATE=$(date +'%Y-%m-%d')
          git commit --allow-empty -m "All Files ${DATE} Edited"

      - name: Push
        run: git push origin main
